ARG CLI_IMAGE
FROM ${CLI_IMAGE} as cli

FROM govcmsdev/test:3.3

COPY --from=cli /app /app

RUN /app/sanitize.sh \
  && rm -rf /app/sanitize.sh

COPY .docker/images/test/drutiny /usr/bin/drutiny

ENV SITE_AUDIT_NAMEPACE fubarhouse
ENV SITE_AUDIT_FILENAME issue-GOVCMS-2414
ENV SITE_AUDIT_VERSION issue/GOVCMS-2414

RUN wget https://github.com/$SITE_AUDIT_NAMEPACE/audit-site/archive/$SITE_AUDIT_VERSION.tar.gz -O SITE_AUDIT_FILENAME.tar.gz \
    && tar -C /tmp -xzvf SITE_AUDIT_FILENAME.tar.gz \
    && rm SITE_AUDIT_FILENAME.tar.gz \
    && mkdir -p /app/sites/all/drutiny \
    && mv /tmp/audit-site-SITE_AUDIT_FILENAME/* /app/sites/all/drutiny \
    && rm -Rf /tmp/audit-site-SITE_AUDIT_FILENAME \
    && php -d memory_limit=-1 /usr/local/bin/composer --working-dir=/app/sites/all/drutiny/ install --ignore-platform-reqs \
    && chmod +x /usr/bin/drutiny

# Add custom drutiny profiles into test for local testing
COPY .docker/images/test/*.yml /app/sites/all/drutiny/Profiles
